from typing import List

from pydantic import BaseModel, Field

from Backend.Schemas.travel_schema import TravelPackage


class ItineraryDay(BaseModel):
    """Recommended itinerary for a single day."""

    day: int = Field(description="Day number starting from 1")

    title: str = Field(
        description="Short title for the day."
    )

    activities: List[str] = Field(
        default_factory=list,
        description="Activities planned for this day.",
    )


class TravelRecommendation(BaseModel):
    """Final recommendation generated by the AI Travel Planner."""

    summary: str = Field(
        description="Brief summary of the overall trip."
    )

    weather_summary: str = Field(
        description="Weather overview and important travel advice."
    )

    currency_summary: str = Field(
        description="Currency conversion summary and exchange information."
    )

    packages: List[TravelPackage] = Field(
        min_items=1,
        description="One or more recommended travel packages.",
    )

    itinerary: List[ItineraryDay] = Field(
        default_factory=list,
        description="Suggested day-wise itinerary.",
    )

    travel_tips: List[str] = Field(
        default_factory=list,
        description="Useful travel recommendations and destination tips.",
    )

    final_recommendation: str = Field(
        description="Concluding recommendation highlighting the best package."
    )