"""Schemas for the Orchestrator node."""

from enum import Enum

from pydantic import BaseModel, Field


class WorkerType(str, Enum):
    """Available worker types."""

    FLIGHT = "flight"
    HOTEL = "hotel"
    ACTIVITY = "activity"
    WEATHER = "weather"
    CURRENCY = "currency"


class WorkerTask(BaseModel):
    """
    Represents a single task assigned to a worker.
    """

    worker: WorkerType = Field(
        description="Worker responsible for executing this task."
    )

    reason: str = Field(
        description="Why this worker is required."
    )


class ExecutionPlan(BaseModel):
    """
    Execution plan generated by the Orchestrator.

    Defines which workers should execute.
    """

    tasks: list[WorkerTask] = Field(
        default_factory=list,
        description="Ordered list of worker tasks."
    )


class OrchestratorOutput(BaseModel):
    """
    Output returned by the Orchestrator node.

    Responsibilities:
    - Decide which workers should execute.
    - Decide whether human approval is required.

    It does NOT modify the TravelPlan.
    """

    execution_plan: ExecutionPlan = Field(
        description="Execution plan for downstream routing."
    )

    hitl_required: bool = Field(
        default=False,
        description="Whether Human-in-the-Loop approval is required."
    )

    hitl_reason: str | None = Field(
        default=None,
        description="Reason for requesting human approval."
    )